pygments: true
markdown: kramdown
permalink: /posts/:title

name: Jef Armstrong
url: http://jefarmstrong.com
avatar_url: /images/buddy_me.jpeg
description: My blog. 
twitter: jefarmstrong
github: jefarmstrong
linkedin: jefarmstrong
work: https://www.cuenotes.com
